create table if not exists public.custom_themes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 80),
  description text not null default '' check (char_length(description) <= 160),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_theme_entries (
  id bigint generated by default as identity primary key,
  theme_id uuid not null references public.custom_themes(id) on delete cascade,
  prompt text not null check (char_length(btrim(prompt)) between 1 and 120),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  unique (theme_id, sort_order)
);

create index if not exists custom_themes_user_created_idx
  on public.custom_themes (user_id, created_at desc);

create index if not exists custom_theme_entries_theme_idx
  on public.custom_theme_entries (theme_id, sort_order);

create unique index if not exists custom_theme_entries_unique_prompt_idx
  on public.custom_theme_entries (theme_id, lower(btrim(prompt)));

alter table public.custom_themes enable row level security;
alter table public.custom_theme_entries enable row level security;

revoke all on table public.custom_themes from anon, authenticated;
revoke all on table public.custom_theme_entries from anon, authenticated;
grant select, insert, update, delete on table public.custom_themes to authenticated;
grant select, insert, update, delete on table public.custom_theme_entries to authenticated;
grant usage, select on sequence public.custom_theme_entries_id_seq to authenticated;

drop policy if exists "Users can read their custom themes" on public.custom_themes;
create policy "Users can read their custom themes"
  on public.custom_themes
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their custom themes" on public.custom_themes;
create policy "Users can create their custom themes"
  on public.custom_themes
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their custom themes" on public.custom_themes;
create policy "Users can update their custom themes"
  on public.custom_themes
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their custom themes" on public.custom_themes;
create policy "Users can delete their custom themes"
  on public.custom_themes
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read their custom theme entries" on public.custom_theme_entries;
create policy "Users can read their custom theme entries"
  on public.custom_theme_entries
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.custom_themes
      where custom_themes.id = custom_theme_entries.theme_id
        and custom_themes.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can create their custom theme entries" on public.custom_theme_entries;
create policy "Users can create their custom theme entries"
  on public.custom_theme_entries
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.custom_themes
      where custom_themes.id = custom_theme_entries.theme_id
        and custom_themes.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can update their custom theme entries" on public.custom_theme_entries;
create policy "Users can update their custom theme entries"
  on public.custom_theme_entries
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.custom_themes
      where custom_themes.id = custom_theme_entries.theme_id
        and custom_themes.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.custom_themes
      where custom_themes.id = custom_theme_entries.theme_id
        and custom_themes.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can delete their custom theme entries" on public.custom_theme_entries;
create policy "Users can delete their custom theme entries"
  on public.custom_theme_entries
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.custom_themes
      where custom_themes.id = custom_theme_entries.theme_id
        and custom_themes.user_id = (select auth.uid())
    )
  );

create or replace function public.create_custom_theme(
  p_title text,
  p_description text,
  p_entries text[]
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_theme_id uuid;
  v_title text := btrim(coalesce(p_title, ''));
  v_description text := btrim(coalesce(p_description, ''));
  v_entry_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  if char_length(v_title) not between 1 and 80 then
    raise exception 'Theme title must be between 1 and 80 characters.';
  end if;

  if char_length(v_description) > 160 then
    raise exception 'Theme description cannot exceed 160 characters.';
  end if;

  select count(*)
  into v_entry_count
  from unnest(coalesce(p_entries, array[]::text[])) as entry(prompt)
  where btrim(prompt) <> '';

  if v_entry_count < 1 then
    raise exception 'Add at least one entry.';
  end if;

  if v_entry_count > 100 then
    raise exception 'A custom theme can contain at most 100 entries.';
  end if;

  if exists (
    select 1
    from unnest(coalesce(p_entries, array[]::text[])) as entry(prompt)
    where btrim(prompt) <> ''
    group by lower(btrim(prompt))
    having count(*) > 1
  ) then
    raise exception 'Each entry must be unique.';
  end if;

  if exists (
    select 1
    from unnest(coalesce(p_entries, array[]::text[])) as entry(prompt)
    where btrim(prompt) <> ''
      and char_length(btrim(prompt)) > 120
  ) then
    raise exception 'Entries cannot exceed 120 characters.';
  end if;

  insert into public.custom_themes (user_id, title, description)
  values (v_user_id, v_title, v_description)
  returning id into v_theme_id;

  insert into public.custom_theme_entries (theme_id, prompt, sort_order)
  select v_theme_id, btrim(entry.prompt), (entry.ordinality - 1)::integer
  from unnest(p_entries) with ordinality as entry(prompt, ordinality)
  where btrim(entry.prompt) <> ''
  order by entry.ordinality;

  return v_theme_id;
end;
$$;

revoke all on function public.create_custom_theme(text, text, text[]) from public, anon;
grant execute on function public.create_custom_theme(text, text, text[]) to authenticated;
