create table if not exists public.themes (
  id text primary key,
  title text not null check (char_length(title) between 1 and 80),
  description text not null check (char_length(description) between 1 and 160),
  icon text not null check (char_length(icon) between 1 and 80),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  accent text not null check (accent ~ '^#[0-9A-Fa-f]{6}$'),
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.theme_prompts (
  id bigint generated by default as identity primary key,
  theme_id text not null references public.themes(id) on delete cascade,
  prompt text not null check (char_length(prompt) between 1 and 120),
  sort_order integer not null default 0,
  unique (theme_id, prompt),
  unique (theme_id, sort_order)
);

create index if not exists theme_prompts_theme_id_idx
  on public.theme_prompts (theme_id);

alter table public.themes enable row level security;
alter table public.theme_prompts enable row level security;

revoke all on table public.themes from anon, authenticated;
revoke all on table public.theme_prompts from anon, authenticated;
grant select on table public.themes to anon, authenticated;
grant select on table public.theme_prompts to anon, authenticated;

drop policy if exists "Published themes are publicly readable" on public.themes;
create policy "Published themes are publicly readable"
  on public.themes
  for select
  to anon, authenticated
  using (is_active);

drop policy if exists "Prompts for published themes are publicly readable"
  on public.theme_prompts;
create policy "Prompts for published themes are publicly readable"
  on public.theme_prompts
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.themes
      where themes.id = theme_prompts.theme_id
        and themes.is_active
    )
  );

insert into public.themes (
  id,
  title,
  description,
  icon,
  color,
  accent,
  sort_order,
  is_active
)
values
  ('movie-icons', 'Movie Icons', 'Stars and characters from the big screen', 'movie-open-star-outline', '#FF775F', '#FFD9D2', 1, true),
  ('superstars', 'Superstars', 'Famous faces from music, sport and TV', 'star-four-points-outline', '#B58BFF', '#E9DDFF', 2, true),
  ('history-makers', 'History Makers', 'Great minds, leaders and trailblazers', 'bank-outline', '#F5C451', '#FFF0C3', 3, true),
  ('wild-animals', 'Wild Animals', 'From tiny critters to jungle giants', 'paw-outline', '#47C8A3', '#CDF5E9', 4, true),
  ('food-drink', 'Food & Drink', 'Delicious dishes and tasty treats', 'silverware-fork-knife', '#FF9C50', '#FFE2C9', 5, true),
  ('anything-goes', 'Anything Goes', 'A wild mix of people, places and things', 'creation-outline', '#59B7F8', '#D4EDFF', 6, true)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  icon = excluded.icon,
  color = excluded.color,
  accent = excluded.accent,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

delete from public.theme_prompts
where theme_id in (
  'movie-icons',
  'superstars',
  'history-makers',
  'wild-animals',
  'food-drink',
  'anything-goes'
);

with seed_prompts (theme_id, prompts) as (
  values
    (
      'movie-icons',
      array[
        'Harry Potter', 'Barbie', 'Indiana Jones', 'Shrek',
        'Wednesday Addams', 'Spider-Man', 'Forrest Gump', 'Darth Vader',
        'The Joker', 'Rocky Balboa', 'Wonder Woman', 'Willy Wonka',
        'James Bond', 'Marty McFly', 'Katniss Everdeen', 'Jack Sparrow'
      ]::text[]
    ),
    (
      'superstars',
      array[
        'Taylor Swift', 'Lionel Messi', 'Beyoncé', 'Dwayne Johnson',
        'Adele', 'Cristiano Ronaldo', 'Lady Gaga', 'LeBron James',
        'Rihanna', 'Gordon Ramsay', 'Serena Williams', 'Ed Sheeran',
        'Zendaya', 'Usain Bolt', 'Billie Eilish', 'David Beckham'
      ]::text[]
    ),
    (
      'history-makers',
      array[
        'Albert Einstein', 'Cleopatra', 'Leonardo da Vinci', 'Marie Curie',
        'Napoleon', 'Frida Kahlo', 'William Shakespeare', 'Amelia Earhart',
        'Nelson Mandela', 'Joan of Arc', 'Isaac Newton', 'Rosa Parks',
        'Wolfgang Mozart', 'Martin Luther King Jr.', 'Vincent van Gogh',
        'Florence Nightingale'
      ]::text[]
    ),
    (
      'wild-animals',
      array[
        'Giraffe', 'Penguin', 'Kangaroo', 'Octopus',
        'Chameleon', 'Gorilla', 'Flamingo', 'Crocodile',
        'Sloth', 'Dolphin', 'Peacock', 'Hippopotamus',
        'Meerkat', 'Polar Bear', 'Rhinoceros', 'Red Panda'
      ]::text[]
    ),
    (
      'food-drink',
      array[
        'Pizza', 'Sushi', 'Ice Cream', 'Tacos',
        'Croissant', 'Spaghetti', 'Popcorn', 'Pancakes',
        'Cheeseburger', 'Watermelon', 'Hot Chocolate', 'Pretzel',
        'Cupcake', 'French Fries', 'Avocado Toast', 'Apple Pie'
      ]::text[]
    ),
    (
      'anything-goes',
      array[
        'The Eiffel Tower', 'A Firefighter', 'TikTok', 'The Moon',
        'A Roller Coaster', 'Sherlock Holmes', 'A Birthday Cake',
        'Mount Everest', 'A Pirate', 'The Internet', 'A Snowman',
        'A Magician', 'The Olympics', 'A Robot', 'A Superhero',
        'A Time Machine'
      ]::text[]
    )
)
insert into public.theme_prompts (theme_id, prompt, sort_order)
select seed_prompts.theme_id, prompt, ordinality::integer
from seed_prompts
cross join lateral unnest(seed_prompts.prompts)
  with ordinality as prompt_rows(prompt, ordinality);
